#!/usr/bin/env ruby

puts "==> Clean Nim exec files"

filenames = Dir.glob("*.nim")

filenames.each do |filename|
  programfile = File.basename(filename, ".nim")
  cmd = "rm -i #{programfile}"
  puts "==> [EXEC] #{cmd}"
  system(cmd)
end
