# File: Rakefile
# Usage: rake

require_relative 'tasks/install'
require_relative 'tasks/build'

# Define tasks
desc 'Default action => check'
task :default do
  Rake::Task['install:check'].invoke
end

desc 'Show rake help'
task :help do
  system('rake -T')
end
