# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "iloveruby" do |i|
    i.vm.box = "generic/opensuse15"
    i.vm.hostname = "iloveruby.iespto"
    i.vm.network "public_network", bridge: [
      "wlan0",
      "eth0",
    ]

    i.vm.synced_folder "./", "/vagrant"
    i.vm.provision "shell", inline: <<-SHELL
      echo "[INFO] Installing tools..."
      zypper --non-interactive --quiet in vim tree nmap git
      
      echo "[INFO] Installing rails..."
      zypper --non-interactive --quiet in gcc make kernel-devel ruby-devel
      # systemctl stop firewalld
      # systemctl disable firewalld
      gem install rails

      echo "[INFO] Installing sqlite3..."
      zypper --non-interactive --quiet in sqlite3 sqlite3-devel
      zypper --non-interactive --quiet in gcc gcc10-c++
      ln -s /usr/bin/gcc-10 /usr/bin/g++
      gem install mini_racer -v 0.4.0
      echo "alias rails='rails.ruby2.5'" >> /home/vagrant/.alias
    SHELL
    i.vm.provider "virtualbox" do |v|
      v.name = 'iloveruby'
      v.memory = 2048
    end
  end
end
