# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "iloveruby" do |i|
    i.vm.box = "generic/opensuse15"
    i.vm.hostname = "iloveruby.iespto"
    i.vm.network "public_network", bridge: [
      "wlan0",
      "eth0",
    ]

    i.vm.synced_folder "./", "/vagrant"
    i.vm.provision :shell, :path => "install-rails-v2.sh"
    i.vm.provider "virtualbox" do |v|
      v.name = 'iloveruby'
      v.memory = 2048
    end
  end
end
