[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "demo"
version = "0.0.1"
description = "Paquete de prueba"
readme = "README.md"

[project.scripts]
demo = "demo.main:run"
