#!/usr/bin/env ruby
# Install packages on OpenSUSE

require_relative 'lib/installapps/package' # Load library

if ARGV.first == '-s'
  debug = true
elsif ARGV.first == '-r'
  debug = false
else
  puts "Usage:"
  puts "        #{$0} OPTIONS"
  puts "Options:"
  puts "  -s    => Simulate installation."
  puts "  -r    => Run installation."
  exit 0
end

NAMES = <<-EOF
tree nmap git geany
EOF

Package.install(NAMES, debug)
