=begin
https://www.amberbit.com/blog/2014/6/12/calling-c-cpp-from-ruby/

Compilation:
 $ gcc -c -fPIC 01-ffi.c -o 01-ffi.o
 $ gcc -shared -o 01-ffi.so 01-ffi.o
=end

desc 'Default: list'
task :default do
  system("rake -T")
end

desc 'Compile 01'
task :compile01 do
  id="01"
  system("gcc -c -fPIC #{id}-ffi.c -o #{id}-ffi.o")
  system("gcc -shared -o #{id}-ffi.so #{id}-ffi.o")
end

desc 'Clean 01'
task :clean01 do
  id="01"
  system("rm #{id}-ffi.o")
  system("rm #{id}-ffi.so")
end
